### PR TITLE
Fix for Python 3 using six + complete testing

### PR DESCRIPTION
**Pull request by PetrDlouhy**
This PR should solve @kmike's remarks from #3 and #5, it also contains testing from #4 and #6.

It is enough to pull this one.

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
@kmike: I have tried to deal with your remarks. If you think, this would need more work, I could make some more effort.

I can also help with maintaining this repo, if you want.

You should enable this project on Travis before merging this.

**Comment by kmike** [comment]
Great, thanks @PetrDlouhy!

**Comment by kmike** [comment]
I've invited you as a collaborator, but if that's OK I can transfer repo to you as well, or create a github org. Do you have a pypi account, so that I can add you there as well?

**Comment by PetrDlouhy** [comment]
I am OK with the transfer. My pypi account is `petr.dlouhy`. Thaks!

**Comment by kmike** [comment]
@PetrDlouhy Thanks! Could you try removing your fork first? Transfer fails because there is a repo with the same name in your account.

**Comment by PetrDlouhy** [comment]
OK, I removed it.

**Pull request merged**
