### PR TITLE
fixes for Python 3

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
Hello, how about this PR. Can you merge it please?

**Comment by edmcdonagh** [comment]
Hello @kmike - would you be willing to accept this pull request and push to pypi? It's one of the few packages that would stop me porting OpenREM to python 3...

**Comment by santiagomalter** [comment]
Hello @kmike, it would be great to accept this PR and eventually release on PyPi. :)

**Comment by kmike** [comment]
Hey guys, 

The pull request has a small issue - unicode values in Python 2 are no longer valid after this PR.

Unfortunately I don't have time to support django-qsstats-magic; if anyone wants to help drop me a note at kmike84@gmail.com.

**Comment by PetrDlouhy** [comment]
Hi @kmike, I made PR from @timur-orudzhov repository. It seems, that is made in Python 2 compatible way.

**Pull request closed without merging**
